import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({results}) {
  
  return (
    <div>
      <Head>
        <title>Plexi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* NavBar */}
      <Nav />

      {/* API Results */}
      <Results results={results}/>
    </div>
  );
}

//SSR funcitons

export async function getServerSideProps(context) {
  //get genre from url passed as context.
  const genre = context.query.genre;

  //Create a request to tmdb
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json())

  //Return the data to components.
  return{
    props:{
      results: request.results
    }
  }
}
